sudo: required
services:
  - docker

before_install:
  - docker build -t gellevenkat/react_complex_app -f ./client/Dockerfile.dev ./client

#Here whatever the scripts we need to run can be specified.
script:
  - docker run gellevenkat/react_complex_app npm test -- --coverage
# after success will create the below folders
after_success:
  - docker build -t gellevenkat/multi-client ./client
  - docker build -t gellevenkat/multi-nginx ./nginx
  - docker build -t gellevenkat/multi-server ./server
  - docker build -t gellevenkat/multi-worker ./worker

# Log in to your docker CLI
-echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

- docker push -t gellevenkat/multi-client
- docker push -t gellevenkat/multi-nginx
- docker push -t gellevenkat/multi-server
- docker push -t gellevenkat/multi-worker
#the above code is to push the docker images to hub.